import './globals.css'
import Header from '@/app/components/layouts/header'
export const metadata = {
  title: 'Panaverse Dao',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
       <Header />
        {children}
        </body>
    </html>
  )
}
